Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,32 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      # Generate a random number between -10 and 10
+      - name: Generate a random number
+        id: random-number
+        run: echo "::set-output name=value::$(shuf -i -10-10 -n 1)"
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      # Check if the random number is negative or positive
+      - name: Check if the random number is negative or positive
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if [ ${{ steps.random-number.outputs.value }} -lt 0 ]
+          then
+            echo "The random number is negative. The job will succeed."
+            exit 0
+          else
+            echo "The random number is positive. The job will fail."
+            exit 1
+          fi
